# Generated by Django 4.1.2 on 2022-10-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='catalog/images/'),
        ),
    ]
